@startsalt
{+
	{
		12年 7月|.
		.|/ 99年
	}

	{
		{#
				{
					1位
					〇 ももたろ社長
					99,999,999百万円
				}
				{
					3位
					貧 やしひめ社長
					99,999,999百万円
				}
				{
					2位
					〇 きんたろ社長
					99,999,999百万円
				}
				{
					4位
					〇 ＭＭＭＭ社長
					99,999,999百万円
				}
		}
		12年終了時点
	}
}
@endsalt
